<?php

function backoffice_thinking_basic_page_and_paragraphs_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ( in_array($form_id, ['node_landing_form', 'node_page_form']) ) {
    //dpm($form['ds_switch_view_mode']['ds_switch']);
    $entity = $form_state->getFormObject()->getEntity();
    if ($entity->isNew()) {
      $entity->ds_switch->value = 'view_mode_selector';
    }
  }
}
